package inweb.modelos_html;

import innui.bases;
import innui.modelos.errores.oks;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author emilio
 */
public class html_escapes extends bases {
    public static Map<String, Character> escapes_mapa = new HashMap<>() {
        {
            put("&Tab;", '\t');
            put("&NewLine;", '\n');
            put("&nbsp;", ' ');
            put("&quot;", '"');
            put("&amp;", '&');
            put("&lt;", '<');
            put("&gt;", '>');
            put("&nbsp;", ' ');
            put("&iexcl;", '¡');
            put("&cent;", '¢');
            put("&pound;", '£');
            put("&curren;", '¤');
            put("&yen;", '¥');
            put("&brvbar;", '¦');
            put("&sect;", '§');
            put("&uml;", '¨');
            put("&copy;", '©');
            put("&ordf;", 'ª');
            put("&laquo;", '«');
            put("&not;", '¬');
            put("&shy;", '­');
            put("&reg;", '®');
            put("&macr;", '¯');
            put("&deg;", '°');
            put("&plusmn;", '±');
            put("&sup2;", '²');
            put("&sup3;", '³');
            put("&acute;", '´');
            put("&micro;", 'µ');
            put("&para;", '¶');
            put("&dot;", '·');
            put("&cedil;", '¸');
            put("&sup1;", '¹');
            put("&ordm;", 'º');
            put("&raquo;", '»');
            put("&frac14;", '¼');
            put("&frac12;", '½');
            put("&frac34;", '¾');
            put("&iquest;", '¿');
            put("&Agrave;", 'À');
            put("&Aacute;", 'Á');
            put("&Acirc;", ' ');
            put("&Atilde;", 'Ã');
            put("&Auml;", 'Ä');
            put("&Aring;", 'Å');
            put("&AElig;", 'Æ');
            put("&Ccedil;", 'Ç');
            put("&Egrave;", 'È');
            put("&Eacute;", 'É');
            put("&Ecirc;", 'Ê');
            put("&Euml;", 'Ë');
            put("&Igrave;", 'Ì');
            put("&Iacute;", 'Í');
            put("&Icirc;", 'Î');
            put("&Iuml;", 'Ï');
            put("&ETH;", 'Ð');
            put("&Ntilde;", 'Ñ');
            put("&Ograve;", 'Ò');
            put("&Oacute;", 'Ó');
            put("&Ocirc;", 'Ô');
            put("&Otilde;", 'Õ');
            put("&Ouml;", 'Ö');
            put("&times;", '×');
            put("&Oslash;", 'Ø');
            put("&Ugrave;", 'Ù');
            put("&Uacute;", 'Ú');
            put("&Ucirc;", 'Û');
            put("&Uuml;", 'Ü');
            put("&Yacute;", 'Ý');
            put("&THORN;", 'Þ');
            put("&szlig;", 'ß');
            put("&agrave;", 'à');
            put("&aacute;", 'á');
            put("&acirc;", 'â');
            put("&atilde;", 'ã');
            put("&auml;", 'ä');
            put("&aring;", 'å');
            put("&aelig;", 'æ');
            put("&ccedil;", 'ç');
            put("&egrave;", 'è');
            put("&eacute;", 'é');
            put("&ecirc;", 'ê');
            put("&euml;", 'ë');
            put("&igrave;", 'ì');
            put("&iacute;", 'í');
            put("&icirc;", 'î');
            put("&iuml;", 'ï');
            put("&eth;", 'ð');
            put("&ntilde;", 'ñ');
            put("&ograve;", 'ò');
            put("&oacute;", 'ó');
            put("&ocirc;", 'ô');
            put("&otilde;", 'õ');
            put("&ouml;", 'ö');
            put("&divide;", '÷');
            put("&oslash;", 'ø');
            put("&ugrave;", 'ù');
            put("&uacute;", 'ú');
            put("&ucirc;", 'û');
            put("&uuml;", 'ü');
            put("&yacute;", 'ý');
            put("&thorn;", 'þ');
            put("&yuml;", 'ÿ');
            put("&Amacr;", 'Ā');
            put("&amacr;", 'ā');
            put("&Abreve;", 'Ă');
            put("&abreve;", 'ă');
            put("&Aogon;", 'Ą');
            put("&aogon;", 'ą');
            put("&Cacute;", 'Ć');
            put("&cacute;", 'ć');
            put("&Ccirc;", 'Ĉ');
            put("&ccirc;", 'ĉ');
            put("&Cdot;", 'Ċ');
            put("&cdot;", 'ċ');
            put("&Ccaron;", 'Č');
            put("&ccaron;", 'č');
            put("&Dcaron;", 'Ď');
            put("&dcaron;", 'ď');
            put("&Dstrok;", 'Đ');
            put("&dstrok;", 'đ');
            put("&Emacr;", 'Ē');
            put("&emacr;", 'ē');
            put("&Ebreve;", 'Ĕ');
            put("&ebreve;", 'ĕ');
            put("&Edot;", 'Ė');
            put("&edot;", 'ė');
            put("&Eogon;", 'Ę');
            put("&eogon;", 'ę');
            put("&Ecaron;", 'Ě');
            put("&ecaron;", 'ě');
            put("&Gcirc;", 'Ĝ');
            put("&gcirc;", 'ĝ');
            put("&Gbreve;", 'Ğ');
            put("&gbreve;", 'ğ');
            put("&Gdot;", 'Ġ');
            put("&gdot;", 'ġ');
            put("&Gcedil;", 'Ģ');
            put("&gcedil;", 'ģ');
            put("&Hcirc;", 'Ĥ');
            put("&hcirc;", 'ĥ');
            put("&Hstrok;", 'Ħ');
            put("&hstrok;", 'ħ');
            put("&Itilde;", 'Ĩ');
            put("&itilde;", 'ĩ');
            put("&Imacr;", 'Ī');
            put("&imacr;", 'ī');
            put("&Ibreve;", 'Ĭ');
            put("&ibreve;", 'ĭ');
            put("&Iogon;", 'Į');
            put("&iogon;", 'į');
            put("&Idot;", 'İ');
            put("&inodot;", 'ı');
            put("&imath;", 'ı');
            put("&IJlig;", 'Ĳ');
            put("&ijlig;", 'ĳ');
            put("&Jcirc;", 'Ĵ');
            put("&jcirc;", 'ĵ');
            put("&Kcedil;", 'Ķ');
            put("&kcedil;", 'ķ');
            put("&kgreen;", 'ĸ');
            put("&Lacute;", 'Ĺ');
            put("&lacute;", 'ĺ');
            put("&Lcedil;", 'Ļ');
            put("&lcedil;", 'ļ');
            put("&Lcaron;", 'Ľ');
            put("&lcaron;", 'ľ');
            put("&Lmidot;", 'Ŀ');
            put("&lmidot;", 'ŀ');
            put("&Lstrok;", 'Ł');
            put("&lstrok;", 'ł');
            put("&Nacute;", 'Ń');
            put("&nacute;", 'ń');
            put("&Ncedil;", 'Ņ');
            put("&ncedil;", 'ņ');
            put("&Ncaron;", 'Ň');
            put("&ncaron;", 'ň');
            put("&napos;", 'ŉ');
            put("&ENG;", 'Ŋ');
            put("&eng;", 'ŋ');
            put("&Omacr;", 'Ō');
            put("&omacr;", 'ō');
            put("&Obreve;", 'Ŏ');
            put("&obreve;", 'ŏ');
            put("&Odblac;", 'Ő');
            put("&odblac;", 'ő');
            put("&OElig;", 'Œ');
            put("&oelig;", 'œ');
            put("&Racute;", 'Ŕ');
            put("&racute;", 'ŕ');
            put("&Rcedil;", 'Ŗ');
            put("&rcedil;", 'ŗ');
            put("&Rcaron;", 'Ř');
            put("&rcaron;", 'ř');
            put("&Sacute;", 'Ś');
            put("&sacute;", 'ś');
            put("&Scirc;", 'Ŝ');
            put("&scirc;", 'ŝ');
            put("&Scedil;", 'Ş');
            put("&scedil;", 'ş');
            put("&Scaron;", 'Š');
            put("&scaron;", 'š');
            put("&Tcedil;", 'Ţ');
            put("&tcedil;", 'ţ');
            put("&Tcaron;", 'Ť');
            put("&tcaron;", 'ť');
            put("&Tstrok;", 'Ŧ');
            put("&tstrok;", 'ŧ');
            put("&Utilde;", 'Ũ');
            put("&utilde;", 'ũ');
            put("&Umacr;", 'Ū');
            put("&umacr;", 'ū');
            put("&Ubreve;", 'Ŭ');
            put("&ubreve;", 'ŭ');
            put("&Uring;", 'Ů');
            put("&uring;", 'ů');
            put("&Udblac;", 'Ű');
            put("&udblac;", 'ű');
            put("&Uogon;", 'Ų');
            put("&uogon;", 'ų');
            put("&Wcirc;", 'Ŵ');
            put("&wcirc;", 'ŵ');
            put("&Ycirc;", 'Ŷ');
            put("&ycirc;", 'ŷ');
            put("&Yuml;", 'Ÿ');
            put("&fnof;", 'ƒ');
            put("&circ;", 'ˆ');
            put("&tilde;", '˜');
            put("&Alpha;", 'Α');
            put("&Beta;", 'Β');
            put("&Gamma;", 'Γ');
            put("&Delta;", 'Δ');
            put("&Epsilon;", 'Ε');
            put("&Zeta;", 'Ζ');
            put("&Eta;", 'Η');
            put("&Theta;", 'Θ');
            put("&Iota;", 'Ι');
            put("&Kappa;", 'Κ');
            put("&Lambda;", 'Λ');
            put("&Mu;", 'Μ');
            put("&Nu;", 'Ν');
            put("&Xi;", 'Ξ');
            put("&Omicron;", 'Ο');
            put("&Pi;", 'Π');
            put("&Rho;", 'Ρ');
            put("&Sigma;", 'Σ');
            put("&Tau;", 'Τ');
            put("&Upsilon;", 'Υ');
            put("&Phi;", 'Φ');
            put("&Chi;", 'Χ');
            put("&Psi;", 'Ψ');
            put("&Omega;", 'Ω');
            put("&alpha;", 'α');
            put("&beta;", 'β');
            put("&gamma;", 'γ');
            put("&delta;", 'δ');
            put("&epsilon;", 'ε');
            put("&zeta;", 'ζ');
            put("&eta;", 'η');
            put("&theta;", 'θ');
            put("&iota;", 'ι');
            put("&kappa;", 'κ');
            put("&lambda;", 'λ');
            put("&mu;", 'μ');
            put("&nu;", 'ν');
            put("&xi;", 'ξ');
            put("&omicron;", 'ο');
            put("&pi;", 'π');
            put("&rho;", 'ρ');
            put("&sigmaf;", 'ς');
            put("&sigma;", 'σ');
            put("&tau;", 'τ');
            put("&upsilon;", 'υ');
            put("&phi;", 'φ');
            put("&chi;", 'χ');
            put("&psi;", 'ψ');
            put("&omega;", 'ω');
            put("&thetasym;", 'ϑ');
            put("&upsih;", 'ϒ');
            put("&piv;", 'ϖ');
            put("&ensp;", ' ');
            put("&emsp;", ' ');
            put("&thinsp;", ' ');
            put("&zwnj;", '‌');
            put("&zwj;", '‍');
            put("&lrm;", '‎');
            put("&rlm;", '‏');
            put("&ndash;", '–');
            put("&mdash;", '—');
            put("&lsquo;", '‘');
            put("&rsquo;", '’');
            put("&sbquo;", '‚');
            put("&ldquo;", '“');
            put("&rdquo;", '”');
            put("&bdquo;", '„');
            put("&dagger;", '†');
            put("&Dagger;", '‡');
            put("&bull;", '•');
            put("&hellip;", '…');
            put("&permil;", '‰');
            put("&prime;", '′');
            put("&Prime;", '″');
            put("&lsaquo;", '‹');
            put("&rsaquo;", '›');
            put("&oline;", '‾');
            put("&euro;", '€');
            put("&trade;", '™');
            put("&larr;", '←');
            put("&uarr;", '↑');
            put("&rarr;", '→');
            put("&darr;", '↓');
            put("&harr;", '↔');
            put("&crarr;", '↵');
            put("&forall;", '∀');
            put("&part;", '∂');
            put("&exist;", '∃');
            put("&empty;", '∅');
            put("&nabla;", '∇');
            put("&isin;", '∈');
            put("&notin;", '∉');
            put("&ni;", '∋');
            put("&prod;", '∏');
            put("&sum;", '∑');
            put("&minus;", '−');
            put("&lowast;", '∗');
            put("&radic;", '√');
            put("&prop;", '∝');
            put("&infin;", '∞');
            put("&ang;", '∠');
            put("&and;", '∧');
            put("&or;", '∨');
            put("&cap;", '∩');
            put("&cup;", '∪');
            put("&int;", '∫');
            put("&there4;", '∴');
            put("&sim;", '∼');
            put("&cong;", '≅');
            put("&asymp;", '≈');
            put("&ne;", '≠');
            put("&equiv;", '≡');
            put("&le;", '≤');
            put("&ge;", '≥');
            put("&sub;", '⊂');
            put("&sup;", '⊃');
            put("&nsub;", '⊄');
            put("&sube;", '⊆');
            put("&supe;", '⊇');
            put("&oplus;", '⊕');
            put("&otimes;", '⊗');
            put("&perp;", '⊥');
            put("&sdot;", '⋅');
            put("&lceil;", '⌈');
            put("&rceil;", '⌉');
            put("&lfloor;", '⌊');
            put("&rfloor;", '⌋');
            put("&loz;", '◊');
            put("&spades;", '♠');
            put("&clubs;", '♣');
            put("&hearts;", '♥');
            put("&diams;", '♦');
        }
    };
    /**
     * Convierte los caracteres a su equivalente formato de escape en HTML
     * @param texto
     * @param ok
     * @param extras_array
     * @return
     * @throws Exception 
     */
    public static String poner_escape_HTML(String texto, oks ok, Object ... extras_array) throws Exception {
        StringBuilder resultado_tex = new StringBuilder();
        try {
            char letra;
            for (int i = 0; i < texto.length(); i++) {
                letra = texto.charAt(i);
                switch(letra) {
                case 9 -> resultado_tex.append("&Tab;");
                case 10 -> resultado_tex.append("&NewLine;");
                case 32 -> resultado_tex.append("&nbsp;");
                case 34 -> resultado_tex.append("&quot;");
                case 38 -> resultado_tex.append("&amp;");
                case 60 -> resultado_tex.append("&lt;");
                case 62 -> resultado_tex.append("&gt;");
                case 160 -> resultado_tex.append("&nbsp;");
                case 161 -> resultado_tex.append("&iexcl;");
                case 162 -> resultado_tex.append("&cent;");
                case 163 -> resultado_tex.append("&pound;");
                case 164 -> resultado_tex.append("&curren;");
                case 165 -> resultado_tex.append("&yen;");
                case 166 -> resultado_tex.append("&brvbar;");
                case 167 -> resultado_tex.append("&sect;");
                case 168 -> resultado_tex.append("&uml;");
                case 169 -> resultado_tex.append("&copy;");
                case 170 -> resultado_tex.append("&ordf;");
                case 171 -> resultado_tex.append("&laquo;");
                case 172 -> resultado_tex.append("&not;");
                case 173 -> resultado_tex.append("&shy;");
                case 174 -> resultado_tex.append("&reg;");
                case 175 -> resultado_tex.append("&macr;");
                case 176 -> resultado_tex.append("&deg;");
                case 177 -> resultado_tex.append("&plusmn;");
                case 178 -> resultado_tex.append("&sup2;");
                case 179 -> resultado_tex.append("&sup3;");
                case 180 -> resultado_tex.append("&acute;");
                case 181 -> resultado_tex.append("&micro;");
                case 182 -> resultado_tex.append("&para;");
                case 183 -> resultado_tex.append("&dot;");
                case 184 -> resultado_tex.append("&cedil;");
                case 185 -> resultado_tex.append("&sup1;");
                case 186 -> resultado_tex.append("&ordm;");
                case 187 -> resultado_tex.append("&raquo;");
                case 188 -> resultado_tex.append("&frac14;");
                case 189 -> resultado_tex.append("&frac12;");
                case 190 -> resultado_tex.append("&frac34;");
                case 191 -> resultado_tex.append("&iquest;");
                case 192 -> resultado_tex.append("&Agrave;");
                case 193 -> resultado_tex.append("&Aacute;");
                case 194 -> resultado_tex.append("&Acirc;");
                case 195 -> resultado_tex.append("&Atilde;");
                case 196 -> resultado_tex.append("&Auml;");
                case 197 -> resultado_tex.append("&Aring;");
                case 198 -> resultado_tex.append("&AElig;");
                case 199 -> resultado_tex.append("&Ccedil;");
                case 200 -> resultado_tex.append("&Egrave;");
                case 201 -> resultado_tex.append("&Eacute;");
                case 202 -> resultado_tex.append("&Ecirc;");
                case 203 -> resultado_tex.append("&Euml;");
                case 204 -> resultado_tex.append("&Igrave;");
                case 205 -> resultado_tex.append("&Iacute;");
                case 206 -> resultado_tex.append("&Icirc;");
                case 207 -> resultado_tex.append("&Iuml;");
                case 208 -> resultado_tex.append("&ETH;");
                case 209 -> resultado_tex.append("&Ntilde;");
                case 210 -> resultado_tex.append("&Ograve;");
                case 211 -> resultado_tex.append("&Oacute;");
                case 212 -> resultado_tex.append("&Ocirc;");
                case 213 -> resultado_tex.append("&Otilde;");
                case 214 -> resultado_tex.append("&Ouml;");
                case 215 -> resultado_tex.append("&times;");
                case 216 -> resultado_tex.append("&Oslash;");
                case 217 -> resultado_tex.append("&Ugrave;");
                case 218 -> resultado_tex.append("&Uacute;");
                case 219 -> resultado_tex.append("&Ucirc;");
                case 220 -> resultado_tex.append("&Uuml;");
                case 221 -> resultado_tex.append("&Yacute;");
                case 222 -> resultado_tex.append("&THORN;");
                case 223 -> resultado_tex.append("&szlig;");
                case 224 -> resultado_tex.append("&agrave;");
                case 225 -> resultado_tex.append("&aacute;");
                case 226 -> resultado_tex.append("&acirc;");
                case 227 -> resultado_tex.append("&atilde;");
                case 228 -> resultado_tex.append("&auml;");
                case 229 -> resultado_tex.append("&aring;");
                case 230 -> resultado_tex.append("&aelig;");
                case 231 -> resultado_tex.append("&ccedil;");
                case 232 -> resultado_tex.append("&egrave;");
                case 233 -> resultado_tex.append("&eacute;");
                case 234 -> resultado_tex.append("&ecirc;");
                case 235 -> resultado_tex.append("&euml;");
                case 236 -> resultado_tex.append("&igrave;");
                case 237 -> resultado_tex.append("&iacute;");
                case 238 -> resultado_tex.append("&icirc;");
                case 239 -> resultado_tex.append("&iuml;");
                case 240 -> resultado_tex.append("&eth;");
                case 241 -> resultado_tex.append("&ntilde;");
                case 242 -> resultado_tex.append("&ograve;");
                case 243 -> resultado_tex.append("&oacute;");
                case 244 -> resultado_tex.append("&ocirc;");
                case 245 -> resultado_tex.append("&otilde;");
                case 246 -> resultado_tex.append("&ouml;");
                case 247 -> resultado_tex.append("&divide;");
                case 248 -> resultado_tex.append("&oslash;");
                case 249 -> resultado_tex.append("&ugrave;");
                case 250 -> resultado_tex.append("&uacute;");
                case 251 -> resultado_tex.append("&ucirc;");
                case 252 -> resultado_tex.append("&uuml;");
                case 253 -> resultado_tex.append("&yacute;");
                case 254 -> resultado_tex.append("&thorn;");
                case 255 -> resultado_tex.append("&yuml;");
                case 256 -> resultado_tex.append("&Amacr;");
                case 257 -> resultado_tex.append("&amacr;");
                case 258 -> resultado_tex.append("&Abreve;");
                case 259 -> resultado_tex.append("&abreve;");
                case 260 -> resultado_tex.append("&Aogon;");
                case 261 -> resultado_tex.append("&aogon;");
                case 262 -> resultado_tex.append("&Cacute;");
                case 263 -> resultado_tex.append("&cacute;");
                case 264 -> resultado_tex.append("&Ccirc;");
                case 265 -> resultado_tex.append("&ccirc;");
                case 266 -> resultado_tex.append("&Cdot;");
                case 267 -> resultado_tex.append("&cdot;");
                case 268 -> resultado_tex.append("&Ccaron;");
                case 269 -> resultado_tex.append("&ccaron;");
                case 270 -> resultado_tex.append("&Dcaron;");
                case 271 -> resultado_tex.append("&dcaron;");
                case 272 -> resultado_tex.append("&Dstrok;");
                case 273 -> resultado_tex.append("&dstrok;");
                case 274 -> resultado_tex.append("&Emacr;");
                case 275 -> resultado_tex.append("&emacr;");
                case 276 -> resultado_tex.append("&Ebreve;");
                case 277 -> resultado_tex.append("&ebreve;");
                case 278 -> resultado_tex.append("&Edot;");
                case 279 -> resultado_tex.append("&edot;");
                case 280 -> resultado_tex.append("&Eogon;");
                case 281 -> resultado_tex.append("&eogon;");
                case 282 -> resultado_tex.append("&Ecaron;");
                case 283 -> resultado_tex.append("&ecaron;");
                case 284 -> resultado_tex.append("&Gcirc;");
                case 285 -> resultado_tex.append("&gcirc;");
                case 286 -> resultado_tex.append("&Gbreve;");
                case 287 -> resultado_tex.append("&gbreve;");
                case 288 -> resultado_tex.append("&Gdot;");
                case 289 -> resultado_tex.append("&gdot;");
                case 290 -> resultado_tex.append("&Gcedil;");
                case 291 -> resultado_tex.append("&gcedil;");
                case 292 -> resultado_tex.append("&Hcirc;");
                case 293 -> resultado_tex.append("&hcirc;");
                case 294 -> resultado_tex.append("&Hstrok;");
                case 295 -> resultado_tex.append("&hstrok;");
                case 296 -> resultado_tex.append("&Itilde;");
                case 297 -> resultado_tex.append("&itilde;");
                case 298 -> resultado_tex.append("&Imacr;");
                case 299 -> resultado_tex.append("&imacr;");
                case 300 -> resultado_tex.append("&Ibreve;");
                case 301 -> resultado_tex.append("&ibreve;");
                case 302 -> resultado_tex.append("&Iogon;");
                case 303 -> resultado_tex.append("&iogon;");
                case 304 -> resultado_tex.append("&Idot;");
                case 305 -> resultado_tex.append("&inodot;");
                case 306 -> resultado_tex.append("&IJlig;");
                case 307 -> resultado_tex.append("&ijlig;");
                case 308 -> resultado_tex.append("&Jcirc;");
                case 309 -> resultado_tex.append("&jcirc;");
                case 310 -> resultado_tex.append("&Kcedil;");
                case 311 -> resultado_tex.append("&kcedil;");
                case 312 -> resultado_tex.append("&kgreen;");
                case 313 -> resultado_tex.append("&Lacute;");
                case 314 -> resultado_tex.append("&lacute;");
                case 315 -> resultado_tex.append("&Lcedil;");
                case 316 -> resultado_tex.append("&lcedil;");
                case 317 -> resultado_tex.append("&Lcaron;");
                case 318 -> resultado_tex.append("&lcaron;");
                case 319 -> resultado_tex.append("&Lmidot;");
                case 320 -> resultado_tex.append("&lmidot;");
                case 321 -> resultado_tex.append("&Lstrok;");
                case 322 -> resultado_tex.append("&lstrok;");
                case 323 -> resultado_tex.append("&Nacute;");
                case 324 -> resultado_tex.append("&nacute;");
                case 325 -> resultado_tex.append("&Ncedil;");
                case 326 -> resultado_tex.append("&ncedil;");
                case 327 -> resultado_tex.append("&Ncaron;");
                case 328 -> resultado_tex.append("&ncaron;");
                case 329 -> resultado_tex.append("&napos;");
                case 330 -> resultado_tex.append("&ENG;");
                case 331 -> resultado_tex.append("&eng;");
                case 332 -> resultado_tex.append("&Omacr;");
                case 333 -> resultado_tex.append("&omacr;");
                case 334 -> resultado_tex.append("&Obreve;");
                case 335 -> resultado_tex.append("&obreve;");
                case 336 -> resultado_tex.append("&Odblac;");
                case 337 -> resultado_tex.append("&odblac;");
                case 338 -> resultado_tex.append("&OElig;");
                case 339 -> resultado_tex.append("&oelig;");
                case 340 -> resultado_tex.append("&Racute;");
                case 341 -> resultado_tex.append("&racute;");
                case 342 -> resultado_tex.append("&Rcedil;");
                case 343 -> resultado_tex.append("&rcedil;");
                case 344 -> resultado_tex.append("&Rcaron;");
                case 345 -> resultado_tex.append("&rcaron;");
                case 346 -> resultado_tex.append("&Sacute;");
                case 347 -> resultado_tex.append("&sacute;");
                case 348 -> resultado_tex.append("&Scirc;");
                case 349 -> resultado_tex.append("&scirc;");
                case 350 -> resultado_tex.append("&Scedil;");
                case 351 -> resultado_tex.append("&scedil;");
                case 352 -> resultado_tex.append("&Scaron;");
                case 353 -> resultado_tex.append("&scaron;");
                case 354 -> resultado_tex.append("&Tcedil;");
                case 355 -> resultado_tex.append("&tcedil;");
                case 356 -> resultado_tex.append("&Tcaron;");
                case 357 -> resultado_tex.append("&tcaron;");
                case 358 -> resultado_tex.append("&Tstrok;");
                case 359 -> resultado_tex.append("&tstrok;");
                case 360 -> resultado_tex.append("&Utilde;");
                case 361 -> resultado_tex.append("&utilde;");
                case 362 -> resultado_tex.append("&Umacr;");
                case 363 -> resultado_tex.append("&umacr;");
                case 364 -> resultado_tex.append("&Ubreve;");
                case 365 -> resultado_tex.append("&ubreve;");
                case 366 -> resultado_tex.append("&Uring;");
                case 367 -> resultado_tex.append("&uring;");
                case 368 -> resultado_tex.append("&Udblac;");
                case 369 -> resultado_tex.append("&udblac;");
                case 370 -> resultado_tex.append("&Uogon;");
                case 371 -> resultado_tex.append("&uogon;");
                case 372 -> resultado_tex.append("&Wcirc;");
                case 373 -> resultado_tex.append("&wcirc;");
                case 374 -> resultado_tex.append("&Ycirc;");
                case 375 -> resultado_tex.append("&ycirc;");
                case 376 -> resultado_tex.append("&Yuml;");
                case 402 -> resultado_tex.append("&fnof;");
                case 710 -> resultado_tex.append("&circ;");
                case 732 -> resultado_tex.append("&tilde;");
                case 913 -> resultado_tex.append("&Alpha;");
                case 914 -> resultado_tex.append("&Beta;");
                case 915 -> resultado_tex.append("&Gamma;");
                case 916 -> resultado_tex.append("&Delta;");
                case 917 -> resultado_tex.append("&Epsilon;");
                case 918 -> resultado_tex.append("&Zeta;");
                case 919 -> resultado_tex.append("&Eta;");
                case 920 -> resultado_tex.append("&Theta;");
                case 921 -> resultado_tex.append("&Iota;");
                case 922 -> resultado_tex.append("&Kappa;");
                case 923 -> resultado_tex.append("&Lambda;");
                case 924 -> resultado_tex.append("&Mu;");
                case 925 -> resultado_tex.append("&Nu;");
                case 926 -> resultado_tex.append("&Xi;");
                case 927 -> resultado_tex.append("&Omicron;");
                case 928 -> resultado_tex.append("&Pi;");
                case 929 -> resultado_tex.append("&Rho;");
                case 931 -> resultado_tex.append("&Sigma;");
                case 932 -> resultado_tex.append("&Tau;");
                case 933 -> resultado_tex.append("&Upsilon;");
                case 934 -> resultado_tex.append("&Phi;");
                case 935 -> resultado_tex.append("&Chi;");
                case 936 -> resultado_tex.append("&Psi;");
                case 937 -> resultado_tex.append("&Omega;");
                case 945 -> resultado_tex.append("&alpha;");
                case 946 -> resultado_tex.append("&beta;");
                case 947 -> resultado_tex.append("&gamma;");
                case 948 -> resultado_tex.append("&delta;");
                case 949 -> resultado_tex.append("&epsilon;");
                case 950 -> resultado_tex.append("&zeta;");
                case 951 -> resultado_tex.append("&eta;");
                case 952 -> resultado_tex.append("&theta;");
                case 953 -> resultado_tex.append("&iota;");
                case 954 -> resultado_tex.append("&kappa;");
                case 955 -> resultado_tex.append("&lambda;");
                case 956 -> resultado_tex.append("&mu;");
                case 957 -> resultado_tex.append("&nu;");
                case 958 -> resultado_tex.append("&xi;");
                case 959 -> resultado_tex.append("&omicron;");
                case 960 -> resultado_tex.append("&pi;");
                case 961 -> resultado_tex.append("&rho;");
                case 962 -> resultado_tex.append("&sigmaf;");
                case 963 -> resultado_tex.append("&sigma;");
                case 964 -> resultado_tex.append("&tau;");
                case 965 -> resultado_tex.append("&upsilon;");
                case 966 -> resultado_tex.append("&phi;");
                case 967 -> resultado_tex.append("&chi;");
                case 968 -> resultado_tex.append("&psi;");
                case 969 -> resultado_tex.append("&omega;");
                case 977 -> resultado_tex.append("&thetasym;");
                case 978 -> resultado_tex.append("&upsih;");
                case 982 -> resultado_tex.append("&piv;");
                case 8194 -> resultado_tex.append("&ensp;");
                case 8195 -> resultado_tex.append("&emsp;");
                case 8201 -> resultado_tex.append("&thinsp;");
                case 8204 -> resultado_tex.append("&zwnj;");
                case 8205 -> resultado_tex.append("&zwj;");
                case 8206 -> resultado_tex.append("&lrm;");
                case 8207 -> resultado_tex.append("&rlm;");
                case 8211 -> resultado_tex.append("&ndash;");
                case 8212 -> resultado_tex.append("&mdash;");
                case 8216 -> resultado_tex.append("&lsquo;");
                case 8217 -> resultado_tex.append("&rsquo;");
                case 8218 -> resultado_tex.append("&sbquo;");
                case 8220 -> resultado_tex.append("&ldquo;");
                case 8221 -> resultado_tex.append("&rdquo;");
                case 8222 -> resultado_tex.append("&bdquo;");
                case 8224 -> resultado_tex.append("&dagger;");
                case 8225 -> resultado_tex.append("&Dagger;");
                case 8226 -> resultado_tex.append("&bull;");
                case 8230 -> resultado_tex.append("&hellip;");
                case 8240 -> resultado_tex.append("&permil;");
                case 8242 -> resultado_tex.append("&prime;");
                case 8243 -> resultado_tex.append("&Prime;");
                case 8249 -> resultado_tex.append("&lsaquo;");
                case 8250 -> resultado_tex.append("&rsaquo;");
                case 8254 -> resultado_tex.append("&oline;");
                case 8364 -> resultado_tex.append("&euro;");
                case 8482 -> resultado_tex.append("&trade;");
                case 8592 -> resultado_tex.append("&larr;");
                case 8593 -> resultado_tex.append("&uarr;");
                case 8594 -> resultado_tex.append("&rarr;");
                case 8595 -> resultado_tex.append("&darr;");
                case 8596 -> resultado_tex.append("&harr;");
                case 8629 -> resultado_tex.append("&crarr;");
                case 8704 -> resultado_tex.append("&forall;");
                case 8706 -> resultado_tex.append("&part;");
                case 8707 -> resultado_tex.append("&exist;");
                case 8709 -> resultado_tex.append("&empty;");
                case 8711 -> resultado_tex.append("&nabla;");
                case 8712 -> resultado_tex.append("&isin;");
                case 8713 -> resultado_tex.append("&notin;");
                case 8715 -> resultado_tex.append("&ni;");
                case 8719 -> resultado_tex.append("&prod;");
                case 8721 -> resultado_tex.append("&sum;");
                case 8722 -> resultado_tex.append("&minus;");
                case 8727 -> resultado_tex.append("&lowast;");
                case 8730 -> resultado_tex.append("&radic;");
                case 8733 -> resultado_tex.append("&prop;");
                case 8734 -> resultado_tex.append("&infin;");
                case 8736 -> resultado_tex.append("&ang;");
                case 8743 -> resultado_tex.append("&and;");
                case 8744 -> resultado_tex.append("&or;");
                case 8745 -> resultado_tex.append("&cap;");
                case 8746 -> resultado_tex.append("&cup;");
                case 8747 -> resultado_tex.append("&int;");
                case 8756 -> resultado_tex.append("&there4;");
                case 8764 -> resultado_tex.append("&sim;");
                case 8773 -> resultado_tex.append("&cong;");
                case 8776 -> resultado_tex.append("&asymp;");
                case 8800 -> resultado_tex.append("&ne;");
                case 8801 -> resultado_tex.append("&equiv;");
                case 8804 -> resultado_tex.append("&le;");
                case 8805 -> resultado_tex.append("&ge;");
                case 8834 -> resultado_tex.append("&sub;");
                case 8835 -> resultado_tex.append("&sup;");
                case 8836 -> resultado_tex.append("&nsub;");
                case 8838 -> resultado_tex.append("&sube;");
                case 8839 -> resultado_tex.append("&supe;");
                case 8853 -> resultado_tex.append("&oplus;");
                case 8855 -> resultado_tex.append("&otimes;");
                case 8869 -> resultado_tex.append("&perp;");
                case 8901 -> resultado_tex.append("&sdot;");
                case 8968 -> resultado_tex.append("&lceil;");
                case 8969 -> resultado_tex.append("&rceil;");
                case 8970 -> resultado_tex.append("&lfloor;");
                case 8971 -> resultado_tex.append("&rfloor;");
                case 9674 -> resultado_tex.append("&loz;");
                case 9824 -> resultado_tex.append("&spades;");
                case 9827 -> resultado_tex.append("&clubs;");
                case 9829 -> resultado_tex.append("&hearts;");
                case 9830 -> resultado_tex.append("&diams;");
                default -> resultado_tex.append(letra);
                }
            }
        } catch (Exception e) {
            throw e;
        }
        return resultado_tex.toString();
    }    

    public static String quitar_escape_HTML(String texto, oks ok, Object ... extras_array) throws Exception {
        String resultado = "";
        int i = 0;
        int tam = texto.length();
        int inicio = -1;
        String nombre_escape = "";
        Character letra;
        while (true) {
            if (i >= tam) {
                break;
            }
            letra = texto.charAt(i);
            if (letra == '&') {
                inicio = i;
            }
            if (inicio >= 0) {
                nombre_escape = nombre_escape + texto.charAt(i);
                if (texto.charAt(i) == ';') {
                    letra = escapes_mapa.get(nombre_escape);
                    if (letra == null) {
                        resultado = resultado + texto.charAt(inicio);
                        i = inicio;
                    } else {
                        resultado = resultado + letra;
                    }
                    nombre_escape = "";
                    inicio = -1;
                } else if (inicio + 10 <= i) {
                    resultado = resultado + texto.charAt(inicio);
                    i = inicio;
                    nombre_escape = "";
                    inicio = -1;
                }
            } else {
                resultado = resultado + letra;
            }
            i = i + 1;
        }
        return resultado;
    }
    
}
